# ==============================================================
# SERVICE: Exponer el deployment (en la parte superior)
# ==============================================================
apiVersion: v1
kind: Service
metadata:
  name: sebastianelli-backend3final
spec:
  selector:
    app: sebastianelli-backend3final
  ports:
    - port: 80 # Puerto del service
      targetPort: 8080 # Puerto del contenedor
  type: NodePort # Esto refiere a que hace con las request

---
# ==============================================================
# DEPLOYMENT: Despliegue de la app - PODS
# ==============================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sebastianelli-backend3final-deploy
  labels:
    app: sebastianelli-backend3final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sebastianelli-backend3final
  template:
    metadata:
      labels:
        app: sebastianelli-backend3final
    spec:
      containers:
        - name: sebastianelli-backend3final
          image: luloh/sebastianelli-backend3final:1.0.0-lts
          ports:
            - containerPort: 8080 # puerto interno
          imagePullPolicy: Always
          env:
            - name: MONGO_URL
              value: "mongodb://host.docker.internal:27017/sebastianelli-backend3final"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
          command: ["npm", "run", "start"]
# commands
#kubectl apply -f kube-mock.yaml
#minikube service sebastianelli-backend3final-service --url
#kubectl logs -f deployment/entregafinalb3-deployment
#kubectl get svc sebastianelli-backend3final-service
#kubectl get pods
#kubectl delete -f kube-mock.yaml

